language: cpp
sudo: required
dist: Xenial
addons:
  apt:
    packages:
    - clang-format
    - clang-tidy
    - cppcheck
# before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -y clang-tidy cppcheck
before_script:
- clang-format --version
- cppcheck --version
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make