language: cpp
sudo: required
addons:
  # apt:
  #   packages:
  #   - clang-format
  #   - clang-tidy
  #   - cppcheck
  sources:
    - universe
 before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y clang-tidy
before_script:
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make