language: cpp
distribution: trusty
sudo: required
addons:
  apt:
    packages:
    # - clang-format
    - clang-tidy-3.8
    # - cppcheck
  sources:
   - universe
# before_install:
# - sudo apt-get update
# - sudo apt-get install -y clang-tidy-3.8
before_script:
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make