language: cpp
dist: trusty
sudo: required
addons:
  # apt:
  #   packages:
  #   - clang-format
  #   - clang-tidy
  #   - cppcheck
  #sources:
  #  - universe
before_install:
- sudo apt-get update
- sudo apt-get install -y clang-3.8
- sudo apt-get install -y clang-tidy-3.8
- sudo ln -s clang-tidy-3.8 /usr/bin/clang-tidy
- sudo apt-get install -y cppcheck
- sudo apt-get install -y clang-format-3.8
- sudo ln -s clang-format-3.8 /usr/bin/clang-format
before_script:
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- ls -a
- mkdir testbuild && cd testbuild
- cmake ..
- make
notifications:
  email:
    on_success: never
    on_failure: never