language: cpp
dist: trusty
sudo: required
addons:
  # apt:
  #   packages:
  #   - clang-format
  #   - clang-tidy
  #   - cppcheck
  #sources:
  #  - universe
before_install:
- sudo sed -i '$a deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get install -y --force-yes clang-3.9 lldb-3.9 clang-tidy-3.9 clang-format-3.9
- sudo ln -s clang-tidy-3.9 /usr/bin/clang-tidy
- sudo ln -s clang-format-3.9 /usr/bin/clang-format
- sudo rm -f /usr/bin/clang
- sudo ln -s clang-3.9 /usr/bin/clang
- sudo apt-get install -y cppcheck
before_script:
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- ls -a
- mkdir testbuild && cd testbuild
- cmake ..
- make
notifications:
  email:
    on_success: never
    on_failure: never