language: cpp
dist: trusty
sudo: required
addons:
  # apt:
  #   packages:
  #   - clang-format
  #   - clang-tidy
  #   - cppcheck
  #sources:
  #  - universe
before_install:
- deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main
- deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main
- wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
- apt-get install clang-4.0 lldb-4.0 lld-4.0
# - sudo apt-get update
# - sudo apt-get install -y clang-tidy-3.8
# - sudo ln -s /usr/bin/clang-tidy-3.8 clang-tidy
before_script:
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make