language: cpp
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install clang-tidy cppcheck
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make