language: cpp
sudo: required
dist: Xenial
addons:
  apt:
    packages:
    - clang-tidy
    - cppcheck
# before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -y clang-tidy cppcheck
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make