language: cpp
dist: trusty
sudo: required
addons:
  # apt:
  #   packages:
  #   - clang-format
  #   - clang-tidy
  #   - cppcheck
  #sources:
  #  - universe
before_install:
- sudo apt-get update
- sudo apt-get install -y clang-tidy-3.8
- sudo ln -s /usr/bin/clang-tidy-3.8 clang-tidy
before_script:
- cmake --version
- clang-tidy --version
compiler:
- clang
- gcc
os:
- linux
script:
- mkdir build && cd build
- cmake ..
- make